version: '2'
services:

  trade_application:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    entrypoint: dockerize -wait tcp://trade_application_db:5432
    depends_on:
      - trade_application_db
    command: /app/start.sh

  trade_application_db:
    image: postgres:11
    restart: always
    env_file: .env
