version: '2'
services:

  trade_application:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    entrypoint: dockerize -wait tcp://trade_application_db:5432 -wait tcp://trade_application_redis:6379 -timeout 120s
    depends_on:
      - trade_application_db
      - trade_application_redis
      - trade_application_celery
    command: /app/scripts/start.sh

  trade_application_db:
    image: postgres:11
    restart: always
    volumes:
      - ../db-trade-tariff-reference/db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file: .env

  trade_application_redis:
    image: redis:3.2
    restart: always
    ports:
      - "6378:6379"

  trade_application_celery:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://trade_application_db:5432 -wait tcp://trade_application_redis:6379 -timeout 120s
    env_file: .env
    command: watchmedo auto-restart -d . -R -p '*.py' -- celery worker -A config -l info -Q celery -B