# Generated by Django 2.2.2 on 2019-08-21 10:23

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_auto_20190816_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaptersSections',
            fields=[
                ('goods_nomenclature_sid', models.IntegerField(primary_key=True, serialize=False)),
                ('section_id', models.IntegerField()),
            ],
            options={
                'db_table': 'chapters_sections',
                'managed': settings.MANAGE_TARIFF_DATABASE,
            },
        ),
    ]
