# Generated by Django 2.2.2 on 2019-08-07 12:47
from datetime import datetime

from django.db import migrations
from django.conf import settings
from trade_tariff_reference.core.utils import load_data_from_sql


BREXIT_VALIDITY_START_DATE = datetime(2019, 3, 29, 0, 0, 0)
BREXIT_VALIDITY_END_DATE = datetime(2019, 12, 31, 0, 0, 0)


def load_database_function(apps, schema_editor):
    # Only run if the tariff database is managed.
    # This skips this migration for testing as we pretend in testing that the view
    # is a database model so we don't want to create the database view.
    if settings.MANAGE_TARIFF_DATABASE:
        return

    context_dict = {
        'validity_start_date': BREXIT_VALIDITY_START_DATE.strftime('%Y-%m-%d'),
        'validity_end_date': BREXIT_VALIDITY_END_DATE.strftime('%Y-%m-%d %H:%M:%S')
    }

    load_data_from_sql('goods_nomenclature_export_brexit.sql', context_dict, 'tariff')
    load_data_from_sql('document_database_views.sql', context_dict, 'tariff')


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0005_chapterssections'),
    ]

    operations = [
        migrations.RunPython(load_database_function, migrations.RunPython.noop),
    ]
