# Generated by Django 2.2.5 on 2019-10-08 09:37

from datetime import datetime
from django.db import migrations
from django.conf import settings
from trade_tariff_reference.core.utils import load_data_from_sql

BREXIT_VALIDITY_START_DATE = datetime(2018, 1, 1, 0, 0, 0)
BREXIT_VALIDITY_END_DATE = datetime(2019, 12, 31, 0, 0, 0)


def load_database_view(apps, schema_editor):
    # Only run if the tariff database is managed.
    # This skips this migration for testing as we pretend in testing that the view
    # is a database model so we don't want to create the database view.
    if settings.MANAGE_TARIFF_DATABASE:
        return

    load_data_from_sql('measures_real_end_dates.sql', dict(), 'tariff')

    brexit_context_dict = {
        'validity_start_date': BREXIT_VALIDITY_START_DATE.strftime('%Y-%m-%d %H:%M:%S'),
        'validity_end_date': BREXIT_VALIDITY_END_DATE.strftime('%Y-%m-%d %H:%M:%S')
    }
    load_data_from_sql('goods_nomenclature_export_brexit.sql', brexit_context_dict, 'tariff')

    load_data_from_sql('document_database_views.sql', brexit_context_dict, 'tariff')


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0006_auto_20190828_1007'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS django', migrations.RunSQL.noop),
        migrations.RunPython(load_database_view, migrations.RunPython.noop),
    ]
