# Generated by Django 2.2.6 on 2019-10-11 08:49

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0007_django_views_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCurrentMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('measure_sid', models.IntegerField(blank=True, null=True)),
                ('geographical_area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reformat_regulation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('regulation_id', models.TextField(blank=True, null=True)),
                ('regulation_id_full', models.TextField(blank=True, null=True)),
                ('goods_nomenclature_item_id', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_code_type_id', models.TextField(blank=True, null=True)),
                ('additional_code_id', models.CharField(blank=True, max_length=3, null=True)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('national', models.BooleanField(blank=True, null=True)),
                ('reduction_indicator', models.IntegerField(blank=True, null=True)),
                ('measure_generating_regulation_role', models.IntegerField(blank=True, null=True)),
                ('measure_generating_regulation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('justification_regulation_role', models.IntegerField(blank=True, null=True)),
                ('justification_regulation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stopped_flag', models.BooleanField(blank=True, null=True)),
                ('geographical_area_sid', models.IntegerField(blank=True, null=True)),
                ('goods_nomenclature_sid', models.IntegerField(blank=True, null=True)),
                ('additional_code_sid', models.IntegerField(blank=True, null=True)),
                ('export_refund_nomenclature_sid', models.IntegerField(blank=True, null=True)),
                ('regulation_group_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"django"."measures_real_end_dates"',
                'managed': settings.MANAGE_TARIFF_DATABASE,
            },
        ),
    ]
