# Generated by Django 2.2.6 on 2019-10-08 13:49

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0007_django_views_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCurrentMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('geographical_area_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"django"."measures_real_end_dates"',
                'managed': settings.MANAGE_TARIFF_DATABASE,
            },
        ),
    ]
