# Generated by Django 2.2.2 on 2019-06-28 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('agreement_name', models.CharField(max_length=1024)),
                ('agreement_date', models.DateField()),
                ('table_per_country', models.IntegerField()),
                ('version', models.CharField(max_length=20)),
                ('country_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('reg_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=None)),
                ('meursing_reduction', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
