# Generated by Django 2.2.2 on 2019-07-24 13:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Unique ID')),
                ('country_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None)),
                ('gegraphical_area', models.CharField(blank=True, max_length=200, null=True)),
                ('agreement_name', models.CharField(max_length=1024, verbose_name='Agreement title')),
                ('agreement_date', models.DateField()),
                ('version', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_order_number_id', models.CharField(max_length=120)),
                ('method', models.CharField(max_length=120)),
                ('y1_balance', models.CharField(blank=True, max_length=120, null=True)),
                ('yx_balance', models.CharField(blank=True, max_length=120, null=True)),
                ('yx_start', models.DateField(blank=True, null=True)),
                ('measurement_unit_code', models.CharField(blank=True, max_length=120, null=True)),
                ('origin_quota', models.CharField(blank=True, max_length=120, null=True)),
                ('addendum', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Agreement')),
            ],
        ),
    ]
