# Generated by Django 2.2.2 on 2019-07-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_documenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_order_number_id', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('year_start_balance', models.IntegerField(blank=True, null=True)),
                ('opening_balance', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=1000, null=True)),
                ('addendum', models.CharField(blank=True, max_length=1000, null=True)),
                ('quota_type', models.CharField(choices=[('F', 'FCFS'), ('L', 'Licensed')], max_length=20)),
                ('is_origin_quota', models.BooleanField(default=False)),
                ('measurement_unit_code', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='schedule.Agreement')),
            ],
        ),
    ]
