# Generated by Django 2.2.2 on 2019-08-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_extendedquota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='geographical_area',
        ),
    ]
