# Generated by Django 2.2.2 on 2019-08-08 11:41

from django.db import migrations, models


def update_document_status(apps, schema_editor):
    Agreement = apps.get_model('schedule', 'Agreement')
    agreements = Agreement.objects.filter(document_created_at__isnull=False)
    agreements.update(document_status='available')


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_agreement_geographical_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenthistory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Document Histories'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='document_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('generating', 'Generating')], default='unavailable', max_length=20),
        ),
        migrations.RunPython(update_document_status, migrations.RunPython.noop),
    ]
