# Generated by Django 2.2.2 on 2019-08-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190812_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatinTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_order_number_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_order_number_id', models.CharField(max_length=120)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalQuotaSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duty', models.CharField(max_length=1000)),
                ('seasonal_quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='schedule.SeasonalQuota')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
