# Generated by Django 2.2.2 on 2019-08-23 11:57

from django.db import migrations, models
import django.db.models.deletion
import trade_tariff_reference.schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_latinterm_seasonalquota_seasonalquotaseason_specialnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('schedule_document', models.FileField(blank=True, null=True, storage=trade_tariff_reference.schedule.models.MFNScheduleStorage(), upload_to='')),
                ('schedule_document_created_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_document_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('generating', 'Generating')], default='unavailable', max_length=20)),
                ('classification_document', models.FileField(blank=True, null=True, storage=trade_tariff_reference.schedule.models.MFNClassificationStorage(), upload_to='')),
                ('classification_document_created_at', models.DateTimeField(blank=True, null=True)),
                ('classification_document_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('generating', 'Generating')], default='unavailable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, storage=trade_tariff_reference.schedule.models.ChapterNoteStorage(), upload_to='')),
                ('document_created_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='schedule.Chapter')),
            ],
            options={
                'ordering': ('chapter__id',),
            },
        ),
    ]
