# Generated by Django 2.2.2 on 2019-08-29 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_chapter_chapternote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentHistory',
            new_name='AgreementDocumentHistory',
        ),
        migrations.AlterModelOptions(
            name='agreementdocumenthistory',
            options={'verbose_name_plural': 'Agreement Document Histories'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='classification_document_check_sum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='schedule_document_check_sum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapternote',
            name='document_check_sum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ChapterDocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('change', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('forced', models.BooleanField()),
                ('remote_file_name', models.CharField(blank=True, max_length=300, null=True)),
                ('chapter_type', models.CharField(choices=[('schedule', 'Schedule'), ('classification', 'Classification')], max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapter')),
            ],
            options={
                'verbose_name_plural': 'Chapter Document Histories',
            },
        ),
    ]
