# Generated by Django 2.2.5 on 2019-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190904_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='display_section_heading',
            field=models.BooleanField(default=False),
        ),
    ]
