# Generated by Django 2.2.5 on 2019-10-07 15:00

from django.db import migrations, models
import trade_tariff_reference.schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_chapter_display_section_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFNTableOfContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, storage=trade_tariff_reference.schedule.models.MFNTableOfContentStorage(), upload_to='')),
                ('document_created_at', models.DateTimeField(blank=True, null=True)),
                ('document_check_sum', models.CharField(blank=True, max_length=32, null=True)),
                ('document_type', models.CharField(choices=[('schedule', 'Schedule'), ('classification', 'Classification')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MFN Table of contents',
            },
        ),
        migrations.AlterModelOptions(
            name='mfndocument',
            options={'verbose_name_plural': 'MFN Documents'},
        ),
    ]
